// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbb7gzTfTwWuBrdeN10U95HA20K05_ZJI',
    appId: '1:928610520931:web:467e6bf8607a70e5428d56',
    messagingSenderId: '928610520931',
    projectId: 'fasum-app-9cf31',
    authDomain: 'fasum-app-9cf31.firebaseapp.com',
    storageBucket: 'fasum-app-9cf31.appspot.com',
    measurementId: 'G-XQT43JF17B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVhVJhix8RMGSbrud-grJNoqrUkebUe8g',
    appId: '1:928610520931:android:edabf3e8af1a2049428d56',
    messagingSenderId: '928610520931',
    projectId: 'fasum-app-9cf31',
    storageBucket: 'fasum-app-9cf31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBJrtpoZ8A-uPYC2R8_dEyM9VtxvD9q-U',
    appId: '1:928610520931:ios:f62e867b983e86e7428d56',
    messagingSenderId: '928610520931',
    projectId: 'fasum-app-9cf31',
    storageBucket: 'fasum-app-9cf31.appspot.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBJrtpoZ8A-uPYC2R8_dEyM9VtxvD9q-U',
    appId: '1:928610520931:ios:3d398d45a6477197428d56',
    messagingSenderId: '928610520931',
    projectId: 'fasum-app-9cf31',
    storageBucket: 'fasum-app-9cf31.appspot.com',
    iosBundleId: 'com.example.fasum.RunnerTests',
  );
}
