// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC17RJXpI3Ifxp4Zm9LQoxVkIHLHHH0Cnc',
    appId: '1:341161918295:web:06e47adfbe12b2a8c44812',
    messagingSenderId: '341161918295',
    projectId: 'fasum-app-455e3',
    authDomain: 'fasum-app-455e3.firebaseapp.com',
    storageBucket: 'fasum-app-455e3.appspot.com',
    measurementId: 'G-ZBZWDV3CMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmmHwVYKFGkr0dk6zsN8vRP0k6tPAvxSs',
    appId: '1:341161918295:android:3bf1ee442921d589c44812',
    messagingSenderId: '341161918295',
    projectId: 'fasum-app-455e3',
    storageBucket: 'fasum-app-455e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW8FkZ5T2TzKZS0HbJL69sC9SY-0Kz1X8',
    appId: '1:341161918295:ios:bda2adef0aaa9306c44812',
    messagingSenderId: '341161918295',
    projectId: 'fasum-app-455e3',
    storageBucket: 'fasum-app-455e3.appspot.com',
    iosClientId: '341161918295-vu5g4dedavd4p79vv46cri6l251452g7.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW8FkZ5T2TzKZS0HbJL69sC9SY-0Kz1X8',
    appId: '1:341161918295:ios:8fa2932625d6cfd8c44812',
    messagingSenderId: '341161918295',
    projectId: 'fasum-app-455e3',
    storageBucket: 'fasum-app-455e3.appspot.com',
    iosClientId: '341161918295-gm46u7o16r209aifpq50bjslv43jndmb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasum.RunnerTests',
  );
}
